### ISSUE TITLE
CSS View Transitions. Or: It's a bird! It's a plane! It's the plan name!

### ISSUE THREAD

**Issue by mrwweb** [grinnellplans/grinnellplans-php#304]
The new [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) is working in Chrome and coming to other browsers. When "cross document transitions" (aka loading a new page) are applied, it makes sites slightly more app-like and works especially well with light-weight sites, since it only applies when a page load is under a certain relatively small amount of time.

I've been quite interested in these and so worked up a brief experiment using a small bit of style and tiny userscript:

```css
@media (prefers-reduced-motion: no-preference) {
        /* opts page into view transitions */
	@view-transition {
		navigation: auto;
	}
	/* sets target for planname transition on page load */
	.username .value {
		view-transition-name: planname;
	}
}
```

```js
// unset planname view-transition-name so it can be used elsewhere
const planName = document.querySelector('.username .value');
if( planName ) {
    planName.style.viewTransitionName = "none";
}

// set all links to plans on the page to the "planname" view-transition-name
const planLinks = document.querySelectorAll('a[href^="read.php?searchname="]');
planLinks.forEach( (link) => {
    link.addEventListener('click', (e) => {
        e.target.style.viewTransitionName = 'planname';
    })
});
```

Here is a video of the result:

https://cldup.com/887nsVbkhw.mp4

Pretty cool, right!?

You'll note that it occasionally does not show the `planname` transition but does seem to (almost?) always do the fade-out/fade-in transition. Seems fine to me. #ProgressiveEnhancement

We could run this on plans easily by adding that script and CSS at any time, and might consider adding a few more named transition elements if we could think of some good ones (though, I'm not sure I can).

Is this too opinionated? Does anyone care? I'm curious what other people think.

The only change I'd definitely want to make is to prevent view transitions from running for anyone with `prefers-reduced-motion` set in their browser.
